name: Continuous Delivery
on:
  workflow_call:

jobs:
  ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8.0.0
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: application

      - uses: actions/checkout@v3

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_SSH_USER }}
          # REMOTE_PORT: ${{ secrets.SERVER_SSH_PORT }}
          TARGET: /home/${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "postgres-data"
