name: Continuous Delivery
on:
  workflow_call:

jobs:
  ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8.0.0
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: application

      - uses: actions/checkout@v3

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_SSH_USER }}
          # REMOTE_PORT: ${{ secrets.SERVER_SSH_PORT }}
          TARGET: /home/${{ secrets.SERVER_SSH_USER }}
          EXCLUDE: "postgres-data"

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_USER=${{ secrets.DB_USER }}
            export DB_PW=${{ secrets.DB_PW }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export DB_SSL=${{ secrets.DB_SSL }}
            export PORT=8000
            chmod +x main
            nohup ./main > nohup.out 2> nohup.err < /dev/null &